SupportTicket/Controllers/AdminController.cs
using SupportTicket.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using SupportTicket.ViewModels;

namespace SupportTicket.Controllers
{
    [Authorize(Roles =Roles.Admin)]
    public class AdminController : Controller
    {
        private readonly AppDbContext db;

        public AdminController()
        {
            this.db = new AppDbContext();
        }

        // GET: Admin
        public ActionResult Index()
        {
            var allAssignments = db.AppUsers.Include(c => c.Agent).ToList();
            var groupedResult = allAssignments.GroupBy(x => x.AgentId);
            var assignments = new List<Assignment>();
            foreach (var item in groupedResult)
            {
                var assignData = new Assignment();
                assignData.AgentName = $"Agent {item.Key}";
                foreach (var cust in item)
                {
                    assignData.Customers.Add(cust.Id, cust.Email);
                }
                assignments.Add(assignData);
            }
            return View(assignments);
        }
    }
}

SupportTicket/Controllers/UserController.cs
using SupportTicket.Models;
using SupportTicket.ViewModels;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using Dapper;
using System.Web.Security;

namespace SupportTicket.Controllers
{
    [Authorize]

    public class UserController : Controller
    {
        private readonly AppDbContext db;

        public UserController()
        {
            this.db = new AppDbContext();
        }

        [HttpGet]
        public ActionResult Details()
        {
            var email = User.Identity.Name;
            var customer = db.AppUsers.Include(x => x.Agent).SingleOrDefault(x => x.Email == email);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }
        [HttpGet]
        public ActionResult Exit()
        {
            var email = User.Identity.Name;
            var customer = db.AppUsers.SingleOrDefault(x => x.Email == email);
            if (customer == null)
            {
                return HttpNotFound();
            }
            db.AppUsers.Remove(customer);
            db.SaveChanges();
            FormsAuthentication.SignOut();
            return RedirectToActionPermanent("Index","Home");
            
        }
    }
}

SupportTicket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">CSS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">
                        Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                @if (User.IsInRole(SupportTicket.Models.Roles.Customer))
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Details","User")">My Agent</a>
                    </li>
                }
                else if (User.IsInRole(SupportTicket.Models.Roles.Admin))
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Admin")">Admin</a>
                    </li>
                }
            </ul>

            @if (User.Identity.IsAuthenticated)
            {
                <form method="post" action="/Account/LogOut" class="form-inline my-2 my-lg-0">
                    <a class="text-white mr-1">@User.Identity.Name</a>
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Signout</button>
                </form>
            }
            else
            {
                <a class="text-white" href="@Url.Action("Login","Account")">Login</a>
            }

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -  By PREET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>